config/routes.rb
Cheapdrunk::Application.routes.draw do

  resources :venues do
    resources :reviews, :only => [:create, :destroy]
  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :only => [:show, :index]

  match '/terms', to: 'home#terms_of_use'
end

app/models/venue.rb
# == Schema Information
#
# Table name: venues
#
#  id             :integer         not null, primary key
#  name           :string(255)
#  description    :text
#  street_address :string(255)
#  postcode       :integer
#  suburb         :string(255)
#  url            :string(255)
#  email          :string(255)
#  created_at     :datetime        not null
#  updated_at     :datetime        not null
#  phone_number   :string(255)
#  latitude       :float
#  longitude      :float
#

class Venue < ActiveRecord::Base
  attr_accessible :description, :email, :name, :postcode, :street_address, 
                  :suburb, :url, :phone_number, :trading_times_attributes, :specials_attributes

  has_many :trading_times
  has_many :reviews
  has_many :users, :through => :reviews
  has_many :specials

  accepts_nested_attributes_for :trading_times 
  accepts_nested_attributes_for :specials, allow_destroy: true

  #Validations to ensure clean data

  #before_save { |venue| venue.email   = email.downcase }
  before_save { |venue| venue.url     = url.downcase }
  before_save { |venue| venue.suburb  = suburb.camelcase }

  VALID_EMAIL_REGEX   = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_URL_REGEX     = /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$/ix
  VALID_SUBURB_REGEX  = /^\w[a-zA-Z ]+$/ #Letters only


  validates :email, allow_blank: true, format: { with: VALID_EMAIL_REGEX }
  validates :url, allow_blank: true, format: { with: VALID_URL_REGEX }
  validates :postcode, presence: true, numericality: true, length:{ is: 4 } #Australian post codes are 4 digits
  validates :suburb, presence: true, format: { with: VALID_SUBURB_REGEX }, length:{ maximum: 20, minimum: 3 }
  validates :description, allow_blank: true, length:{ maximum: 500, minimum: 100 }

  #Geocoding for venues

  geocoded_by :full_address
  after_validation :geocode, :if => :address_changed?

  #SEO Friendly URLs
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  #Searchable
  searchable do
    text :name, :postcode, :suburb, :street_address
  end

  def full_address
    address = "#{self.street_address}, #{self.suburb}, #{self.postcode}, Australia"
  end

  def address_changed?
    street_address_changed? || suburb_changed? || postcode_changed?
  end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  #Only admins can add and edit venues etc..
  load_and_authorize_resource

  layout "venue", :except => [:show]

  add_breadcrumb "Homepage", :root_path
  add_breadcrumb "Venues", :venues_path, :title => "Sydney Bars & Pubs"

  def index
    @search = Venue.search do
      fulltext params[:search]
      paginate(:page => params[:page], :per_page => 10)
    end
    @venues = @search.results
  end

  def show
    #Make sure to 301 to the current URL from any old ones
    if request.path != venue_path(@venue)
      redirect_to @venue, status: :moved_permanently
    else
      @venue = Venue.find(params[:id])
      render :layout => "show_venue"
    end
  end

  def new
    @venue = Venue.new
    @venue.trading_times.new 
    @venue.specials.new
  end

  def create
    @venue = Venue.new(params[:venue])
    if @venue.save
      flash[:success] = "Venue sucessfully added"
      redirect_to @venue
    else
      render 'new'
    end
  end

  def update
    @venue = Venue.find(params[:id])
    if @venue.update_attributes(params[:venue])
      flash[:success] = "Venue updated"
      redirect_to @venue
    else
      render 'edit'
    end
  end

end

app/helpers/venues_helper.rb
module VenuesHelper
  def format_distance_from(distance)
    if distance < 1
      distance *= 100
      return number_with_precision(distance, :precision => 0) + " meters"
    else
      return number_with_precision(distance, :precision => 2) + " km"
    end
  end
end

app/views/venues/_fancybox.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $(".fancybox").fancybox();
  });


$(document).ready(function() {
  $(".various").fancybox({
    maxWidth  : 800,
    maxHeight : 600,
    fitToView : false,
    width   : '70%',
    height    : '70%',
    autoSize  : false,
    closeClick  : false,
    openEffect  : 'none',
    closeEffect : 'none'
  });
});</script>

app/views/venues/_form.html.erb
<div class="tabbable "> 
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">Main Details</a></li>
    <li><a href="#tab2" data-toggle="tab">Trading Hours</a></li>
    <li><a href="#tab3" data-toggle="tab">Specials</a></li>
  </ul>
   <%= form_for(@venue) do |f| %>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      <%= render 'shared/error_messages', object: f.object %>
      <%= render 'venue_form', f: f %>
    </div>
    <div class="tab-pane" id="tab2">
      <p> 
        <%= f.fields_for :trading_times do |builder| %>
        <%= render :partial => "trading_times/trading_times_form", 
            :locals => { :f => builder } %>
        <% end %>
      </p>
    </div>

    <div class="tab-pane" id="tab3">
      <%= f.fields_for :specials do |builder| %>
        <%= render :partial => "specials/specials_form", 
            :locals => { :f => builder } %>
      <% end %>
    </div>
    <%= f.submit "Submit Venue", class: "btn btn-large btn-primary" %>

    <% end %>
  </div>
</div>

app/views/venues/_trading_times.html.erb
<% for day in @venue.trading_times %>
  <time itemprop="openingHours" datetime="Mo 
  <%= "#{day.monday_opens_at.strftime('%H:%M')}-#{day.monday_closes_at.strftime('%H:%M')}" %>">
  Monday: <%= "#{day.monday_opens_at.strftime('%l:%M %P')} - #{day.monday_closes_at.strftime('%l:%M %P')}" %> <br>
  <time itemprop="openingHours" datetime="Tu 
  <%= "#{day.tuesday_opens_at.strftime('%H:%M')}-#{day.tuesday_closes_at.strftime('%H:%M')}" %>">
  Tuesday: <%= "#{day.tuesday_opens_at.strftime('%l:%M %P')} - #{day.tuesday_closes_at.strftime('%l:%M %P')}" %> <br>
  <time itemprop="openingHours" datetime="We 
  <%= "#{day.wednesday_opens_at.strftime('%H:%M')}-#{day.wednesday_closes_at.strftime('%H:%M')}" %>">
  Wednesday: <%= "#{day.wednesday_opens_at.strftime('%l:%M %P')} - #{day.wednesday_closes_at.strftime('%l:%M %P')}" %> <br>
  <time itemprop="openingHours" datetime="Th 
  <%= "#{day.thursday_opens_at.strftime('%H:%M')}-#{day.thursday_closes_at.strftime('%H:%M')}" %>">
  Thursday: <%= "#{day.thursday_opens_at.strftime('%l:%M %P')} - #{day.thursday_closes_at.strftime('%l:%M %P')}" %> <br>
  <time itemprop="openingHours" datetime="Fr 
  <%= "#{day.friday_opens_at.strftime('%H:%M')}-#{day.friday_closes_at.strftime('%H:%M')}" %>">
  Friday: <%= "#{day.friday_opens_at.strftime('%l:%M %P')} - #{day.friday_closes_at.strftime('%l:%M %P')}" %> <br>
  <time itemprop="openingHours" datetime="Sa 
  <%= "#{day.saturday_opens_at.strftime('%H:%M')}-#{day.saturday_closes_at.strftime('%H:%M')}" %>">
  Saturday: <%= "#{day.saturday_opens_at.strftime('%l:%M %P')} - #{day.saturday_closes_at.strftime('%l:%M %P')}" %> <br>
  <time itemprop="openingHours" datetime="Su 
  <%= "#{day.sunday_opens_at.strftime('%H:%M')}-#{day.sunday_closes_at.strftime('%H:%M')}" %>">
  Sunday: <%= "#{day.sunday_opens_at.strftime('%l:%M %P')} - #{day.sunday_closes_at.strftime('%l:%M %P')}" %> <br>
<% end %>

app/views/venues/_venue_form.html.erb
<%= f.label :name %>
<%= f.text_field :name, html_options = { :class => "span6" } %>

<%= f.label :email %>
<%= f.text_field :email, html_options = { :class => "span6" } %>

<%= f.label :street_address %>
<%= f.text_field :street_address, html_options = { :class => "span6" } %>

<%= f.label :suburb %>
<%= f.text_field :suburb, html_options = { :class => "span6" } %>

<%= f.label :postcode %>
<%= f.text_field :postcode, html_options = { :class => "span6" } %>

<%= f.label :phone_number %>
<%= f.text_field :phone_number, html_options = { :class => "span6" } %>

<%= f.label :url %>
<%= f.text_field :url, html_options = { :class => "span6" } %>

<%= f.label :description %>
<%= f.text_area :description, html_options = { :class => "span6", :size => "6x6" }  %>

app/views/venues/_venue_management.html.erb
<% if can? :update, @venue %>
<li><b>Admin Links:</b></li>
  <li class="span4"><%= link_to "Delete Venue", venue_path(params[:id]), method: "delete" %></li>
  <li class="span4"><%= link_to "Edit Venue", edit_venue_path %> </li>

<% else %>

<li><b>Advertisement:</b></li>
    <li class="span4">
     <script type="text/javascript"><!--
google_ad_client = "ca-pub-5928836225298236";
/* Cheap Drunk Venues */
google_ad_slot = "5554647790";
google_ad_width = 250;
google_ad_height = 250;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
    </li>

<% end %>

app/views/venues/edit.html.erb
<div class="row">
  <div class="span6 offset3">
    <h1>Update this venue</h1>
      <%= render 'form' %>
  </div>
</div>

app/views/venues/index.html.erb
<h1>Browse Happy Hour Venues</h1>

<div class="template_time"> random: <strong><%= rand(900)+100 %></strong></div>
<div data-pjax-container>

<% @venues.each do |venue| %>
  <div class="listing">
    <div class="listing-header">
      <span class="listing-name">
       <h3> <%= link_to venue.name, venue %> </h3>
      </span>
      <span class="listing-rating">
        
      </span>
    </div>
    <div class="listing-body">
      <span class="listing-logo"><img src="http://placehold.it/80x80"></span>
      <span class="listing-description"><%= truncate(venue.description, :length => 215, :separator => ' ', :omission => '...') %></span>
      <span class="listing-details">
        <%= venue.street_address %> <br>
        <%= venue.suburb %> <br>
        <% if venue.reviews.count > 0 %>
          <%= average_rating_percent(average_rating(venue.id)) %> based on <br>
          <%= pluralize(@venue.reviews.count, 'review') %>
        <% end %>
      </span>
    </div>
  </div>
<% end %>
<nav>
 <%= page_navigation_links @venues %>
</nav>
</div>

app/views/venues/new.html.erb
<div class="row">
  <div class="span6 offset3">
    <h1>Submit a new venue</h1>
      <%= render 'form' %>
  </div>
</div>

app/views/venues/show.html.erb
<%= render 'fancybox' %>
<div itemscope itemtype="http://schema.org/BarOrPub">
  <div class="row">
    <div class="span8">
      <div class="page-header">
       <h1 class="venue-title"><span itemprop="name"><%= @venue.name %></span></h1>
      </div>
      <div class="well" >
        
      <span itemprop="geo" itemscope itemtype="http://schema.org/GeoCoordinates">
        <meta itemprop="latitude" content="<%= @venue.latitude %>" />
        <meta itemprop="longitude" content="<%= @venue.longitude %>" /> </span>
       <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
          <span itemprop="streetAddress" class="address"><b><%= @venue.street_address %></b></span><br>
          <span itemprop="addressLocality" class="address"><b><%= @venue.suburb %></b></span>,
          <span itemprop="postalCode" class="address"><b><%= @venue.postcode %></b></span>
       </div> <!-- end postal address microdata-->
       <p><span itemprop="telephone" class="address"><b><%= @venue.phone_number %></b></span></p>
       <p><a itemprop="url" href="<%= @venue.url %>" rel="nofollow" target="_blank"><%= @venue.url %></a></p>
       <p><small><b><%= @venue.description %></b></small></p>
       <div itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
         <meta itemprop="ratingValue" content="<%= average_rating(@venue.id) %>" />
         <%= display_stars(average_rating(@venue.id)) %> <br>
         Based on <b><span itemprop="reviewCount"><%= pluralize(@venue.reviews.count, 'vote') %></span></b>
       </div>  <!-- end aggregate rating microdata -->

      </div>



  <ul class="thumbnails">
      <li class="span2">
        <span class="thumbnail">
          <img src="http://placehold.it/160x120" alt="">
        </span>
     </li>
    <li class="span2">
        <span class="thumbnail">
          <img src="http://placehold.it/160x120" alt="">
        </span>
    </li>
    <li class="span2">
        <span class="thumbnail">
          <img src="http://placehold.it/160x120" alt="">
        </span>
    </li>
    <li class="span2">
        <span class="thumbnail">
          <img src="http://placehold.it/160x120" alt="">
        </span>
    </li>
    </ul>

    <!-- To be added later
    <h3>Monday</h3>
    <div itemprop="events" itemscope itemtype="http://schema.org/Event">
      <meta itemprop="startDate" content="2016-04-21T20:00">
      <meta itemprop="endDate" content="2016-04-21T20:00">
      <div itemprop="name"><h5>Lunch Special</h5></div>
      <p><span itemprop="description">$7 pizza and beer choose from Margarita, Vegetarian or Spanish and your choice of tap beer or wine.</span></p>
    </div>  end event microdata -->

    </div>
    <div class="span4">
    <ul class="thumbnails">
      <li class="span4">
          <a class="various fancybox.iframe thumbnail" href="http://maps.google.com/?output=embed&amp;z=15&amp;t=m&amp;q=loc:<%= @venue.latitude %>+<%= @venue.longitude %>">


          <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{ @venue.latitude },#{ @venue.longitude }&markers=#{ @venue.latitude },#{ @venue.longitude }&zoom=15&size=360x268&maptype=roadmap&sensor=true", :alt => "Map to #{@venue.name}" %>

        </a>
      </li>   
    <%= render 'venue_management' %>

  <li class="span3">
    <b>Trading Hours:</b>
  </li>
  <li class="span3">
    <%= render 'trading_times' %>
  </li>
  <li class="span3">
    <b>Nearby Venues:</b>
  </li>
  <li class="span3">
    <% @venue.nearbys(5).first(4).each do |close_venue| %>
    <%= link_to close_venue.name, close_venue %><br />
    <%= format_distance_from(close_venue.distance_from(@venue)) %>
    <br/>
    <% end %> 
  </li>
  </ul></div>

  <div class="span8">
    <%= render 'reviews/new' %>
    <%= render 'reviews/view' %>
  </div>  
 </div>
</div><!-- end bar or pub microdata -->

</div>