config/routes.rb
Cheapdrunk::Application.routes.draw do

  resources :venues do
    resources :reviews, :only => [:create, :destroy]
  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :only => [:show, :index]

  match '/terms', to: 'home#terms_of_use'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create  
    @venue = Venue.find(params[:venue_id])
    @review = @venue.reviews.new(params[:review].merge(:user_id => current_user.id))
    
    if @review.save
      flash[:success] = "Thanks for adding your review"
      redirect_to venue_path(params[:venue_id])
    else
      flash[:error] = "Please ensure your review is between 100 - 500 characters"
      redirect_to venue_path(params[:venue_id])
    end
  end

  def destroy
    Review.find(params[:id]).destroy
    flash[:success] = "Review deleted."
    redirect_to venue_path(params[:venue_id])
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def display_stars(star)
    (1..5).inject("") do |output, i|
      output << radio_button_tag('star3',nil, i.eql?(star), :class => 'star', :disabled => true)
    end.html_safe
  end

  def average_rating(venue_id)
    @venue = Venue.find(venue_id)
    @average = 0
    if !@venue.reviews.empty?
      @venue.reviews.each do |review|
      @average = @average + review.rating
      end
      @average / @venue.reviews.count
    end
  end

  def average_rating_percent(average)
    @average_percent = (average.to_f / 5.to_f) * 100
    number_to_percentage(@average_percent, :precision => 0) 
  end
end

app/views/reviews/_new.html.erb
<% if can? :manage, Review %>
<script>
$(function(){
      function analyticsGoal(event) {
            _gaq.push(['_trackEvent', 'Forms', 'Submit', 'VenueReview']);
            
      }
      $("input.btn-primary").click(analyticsGoal);

});
</script>
<%= form_for [@venue, Review.new] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= radio_button_tag("review[rating]", "1", false, :class => "star") %>
  <%= radio_button_tag("review[rating]", "2", false, :class => "star") %>
  <%= radio_button_tag("review[rating]", "3", false, :class => "star") %>
  <%= radio_button_tag("review[rating]", "4", false, :class => "star") %>
  <%= radio_button_tag("review[rating]", "5", false, :class => "star") %>

  <%= f.text_area :comment, :size => "5x5" %>
  <%= f.submit "Submit Review", class: "btn btn-large btn-primary" %>
<% end %>
<% else %>
<p>Please login to leave a comment </p>
<% end %>

app/views/reviews/_view.html.erb
<div class="well">
  <meta itemprop="interactionCount" content="UserComments:<%= @venue.reviews.count %>"/>
  <% for review in @venue.reviews %>
    <div itemprop="review" itemscope itemtype="http://schema.org/Review">
      <div itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
        <span class="rating-foreground" itemprop="ratingValue">
          <meta itemprop="worstRating" content="1"> 
          <meta itemprop="ratingValue" content="<%= review.rating %>" /> 
          <meta itemprop="bestRating" content="5">
        </span> 
      </div>
      <div itemprop="reviewBody" class="reviewBody"><%= review.comment %></div>
      <span itemprop="author" itemscope itemtype="http://schema.org/Person" >
        Reviewed by: 
        <span itemprop="name" ><%= User.find(review.user_id).name %></span></span>
        on 
      <span><meta itemprop="datePublished" content="<%= review.created_at.to_date %>" class="datePublished">
      <%= review.created_at.to_date.to_formatted_s(:long_ordinal)  %></span>
    </div>
    <% if can? :update, @venue %>
      <span class="label label-important delete_review" >
        <%= link_to "Delete Review", venue_review_path(@venue.id, review.id), 
        url_options = { method: "delete", :confirm => "Are you sure?" }%>
        </span>
      <% end %>
  <% end %>
</div>