config/routes.rb
Cheapdrunk::Application.routes.draw do

  resources :venues do
    resources :reviews, :only => [:create, :destroy]
  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :only => [:show, :index]

  match '/terms', to: 'home#terms_of_use'
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Cheapdrunk", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
    <li>
    <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
  <li>
    
    <%= form_tag venues_path, :method => :get, :class => "navbar-search pull-right" do %>
    <%= text_field_tag :search, params[:search], :class => "search-query", :placeholder => "Search" %>
    <% end %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Cheapdrunk" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <script type="text/javascript">  
    var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32477640-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();</script>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/layouts/show_venue.html.erb
<!doctype html xmlns:og="http://ogp.me/ns#" xmlns:fb="https://www.facebook.com/2008/fbml">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Cheapdrunk" %></title>
    <meta name="description" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <meta property="og:title" content="<%= @venue.name %>"/>
    <meta property="og:type" content="bar"/>
    <meta property="og:url" content="<%= url_for(:only_path => false) %>"/>
    <meta property="og:image" content=""/>
    <meta property="og:site_name" content="Cheap Drunk"/>
    <meta property="fb:admins" content="USER_ID"/>
    <meta property="og:description" content="<%= @venue.description %>"/>
    <meta property="og:latitude" content="<%= @venue.latitude %>"/>
    <meta property="og:longitude" content="<%= @venue.longitude %>"/>
    <meta property="og:street-address" content="<%= @venue.street_address %>"/>
    <meta property="og:locality" content="<%= @venue.suburb %>"/>
    <meta property="og:region" content="NSW"/>
    <meta property="og:postal-code" content="<%= @venue.postcode %>"/>
    <meta property="og:country-name" content="Australia"/>
    <script type="text/javascript">  
    var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32477640-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();</script>
  </head>
  <body itemscope itemtype="http://schema.org/WebPage">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
     <div role="main" id="wrap-container" class="container">
      
      <div itemprop="breadcrumb">
        <%= render_breadcrumbs :separator => ' > ' %>
      </div>

      <%= render 'layouts/messages' %>
    
            <%= yield %>

          <footer>

          </footer>
<%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/layouts/venue.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Cheapdrunk" %></title>
    <meta name="description" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <script type="text/javascript">  
    var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32477640-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();</script>
  </head>
  <body itemscope itemtype="http://schema.org/WebPage">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
     <div role="main" id="wrap-container" class="container">
      
      <%= render 'layouts/messages' %>
    
            <%= yield %>

          <footer>

          </footer>
<%= debug(params) if Rails.env.development? %>
  </body>
</html>